### PR TITLE
com.nokia.SensorService.role.json: Add trustLevel

### PR DESCRIPTION
**Pull request by Herrie82**
Fixes: Dec 13 12:27:03 qemux86-64 ls-hubd[242]: [] [pmlog] ls-hubd LSHUB_ROLE_FILE {"FILE":"file_parser.cpp","LINE":195} No trust level specified for application in role file (/usr/share/luna-service2/roles.d/com.nokia.SensorService.role.json)

webOS/LuneOS Specific for for LG's Enhanced ACG that's now being used in webOS OSE and LuneOS.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Review by mlehtima — APPROVED** [review]

**Review by spiiroin — APPROVED** [review]

**Comment by Herrie82** [comment]
@rainemak Can you merge this one too? Then I can drop my local patch ;)

**Comment by rainemak** [comment]
> @rainemak Can you merge this one too? Then I can drop my local patch ;)

Sure @Herrie82. By any chance could you rebase the PR. We'd like to keep merge commits in the history so that we have traceability of the PRs. Thus, github's "Rebase and merge" doesn't really work well.

**Comment by rainemak** [comment]
Looks that some went wrong with the sync. AFAIS it looks that you ran git merge sailfishos/master instead of git rebase sailfishos/master.

**Comment by Herrie82** [comment]
Sorry, messed something up, see (https://github.com/sailfishos/sensorfw/pull/18) instead

**Pull request closed without merging**
